# Site settings
title: Jacopo Greco d'Alceo
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Jacopo Greco d'Alceo artist website
baseurl: "/urban-theme" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jacopogrecodalceo

# Build settings
markdown: kramdown
permalink: pretty
